# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170527_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='username',
            field=models.CharField(default='uknown', max_length=400),
            preserve_default=False,
        ),
    ]
