# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_bar_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='beer_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='discounts',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total',
            field=models.FloatField(),
        ),
    ]
